on:
  push:
    branches:
      - 'main'

name: CI

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - uses: taiki-e/install-action@cargo-llvm-cov
      
      - name: build
        run: cargo build --verbose

      - name: tests with coverage
        run: cargo llvm-cov