on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

name: CI

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            rust:
              - .github/workflows/ci.yml
              - ./**/*.rs
              - Cargo.toml
              - Cargo.lock

      - uses: dtolnay/rust-toolchain@stable
        if: steps.changes.outputs.rust == 'true'
        with:
          components: llvm-tools-preview, rustfmt

      - uses: taiki-e/install-action@cargo-llvm-cov
        if: steps.changes.outputs.rust == 'true'
      
      - name: build
        if: steps.changes.outputs.rust == 'true'
        run: cargo build --verbose

      - name: rustfmt
        if: steps.changes.outputs.rust == 'true'
        run: cargo fmt --check

      - name: tests with coverage
        if: steps.changes.outputs.rust == 'true'
        run: |
          cargo llvm-cov
          cargo llvm-cov report --lcov --output-path lcov.info

      - name: Upload coverage reports to Codecov
        if: steps.changes.outputs.rust == 'true'
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
